const fs = require('fs');

const lines = [
`import { Conversation, User, CV } from '@prisma/client';`,
`import { IWhatsAppProvider } from '../../whatsapp/whatsapp.interface.js';`,
`import { ConversationService } from '../../domain/services/conversation.service.js';`,
`import { CVService } from '../../domain/services/cv.service.js';`,
`import { CvPreviewService } from '../../domain/services/cv-preview.service.js';`,
`import { IntentEngine } from '../../ai/intent/IntentEngine.js';`,
`import { ContextBuilder } from '../../ai/context/ContextBuilder.js';`,
`import { SECTION_REGISTRY, ORDERED_SECTIONS } from './sections/SectionRegistry.js';`,
`import { SectionId, SectionDefinition } from './sections/types.js';`,
`import { ConversationEventBus } from '../events/event-bus.js';`,
`import { ConversationEventType } from '../events/event-types.js';`,
`import { logger } from '../../utils/logger.js';`,
`import { IntentResult } from '../../ai/intent/types.js';`,
`import { SessionMetadata } from './types.js';`,
`import { PDFService } from '../../pdf/pdf.service.js';`,
`import { AuthoringService } from '../../ai/authoring/AuthoringService.js';`,
`import { CVDataUpdater } from './CVDataUpdater.js';`,
``,
`export class FSMEngine {`,
`  private eventBus = ConversationEventBus.getInstance();`,
`  private intentEngine = new IntentEngine();`,
``,
`  constructor(`,
`    private provider: IWhatsAppProvider,`,
`    private convService: ConversationService,`,
`    private cvService: CVService,`,
`    private pdfService: PDFService,`,
`    private authoringService: AuthoringService,`,
`    private cvPreviewService: CvPreviewService`,
`  ) {}`,
``,
`  private async sendMessageAndUpdateMeta(conversationId: string, phone: string, msg: string, meta: SessionMetadata) {`,
`    meta.lastBotMessage = msg;`,
`    await this.saveMeta(conversationId, meta);`,
`    await this.provider.sendMessage(phone, msg);`,
`  }`,
``,
`  public async processMessage(`,
`    user: User,`,
`    conversation: Conversation,`,
`    message: string`,
`  ): Promise<void> {`,
`    const meta = (`,
`      typeof conversation.metadata === 'object' && conversation.metadata !== null`,
`        ? conversation.metadata`,
`        : {}`,
`    ) as SessionMetadata;`,
``,
`    let cv = await this.cvService.getActiveCVForUser(user.id);`,
`    if (!cv) {`,
`      cv = await this.cvService.createCV({ userId: user.id });`,
`    }`,
``,
`    if (!meta.currentSectionId) {`,
`      meta.currentSectionId = 'WELCOME';`,
`      meta.currentFieldId = 'DONE';`,
`    }`,
``,
`    const lang = meta.lang === 'sw' ? 'sw' : 'en';`,
``,
`    if (meta.currentSectionId === 'WELCOME') {`,
`      const section = SECTION_REGISTRY['WELCOME'];`,
`      await this.completeSection(section, conversation, user, lang, cv, meta, false);`,
`      `,
`      const trimmed = message.trim().toLowerCase();`,
`      const isLangChoice = trimmed === '1' || trimmed === '2' || `,
`                           trimmed.includes('swahili') || trimmed.includes('kiswahili') || `,
`                           trimmed.includes('english') || trimmed.includes('en') || trimmed.includes('sw');`,
`      `,
`      if (!isLangChoice) {`,
`        return;`,
`      }`,
`    }`,
``,
`    if (meta.isReviewMode) {`,
`      const handled = await this.handleReviewMode(message, conversation, user, lang, cv, meta);`,
`      if (handled) return;`,
`    }`,
``,
`    // Prepare expected field info for IntentEngine`,
`    let expectedField: string | undefined = undefined;`,
`    let expectedFieldType: string | undefined = undefined;`,
`    let currentQuestion: string | undefined = undefined;`,
`    let fieldDescription: string | undefined = undefined;`,
`    let validationHints: string | undefined = undefined;`,
``,
`    const currentSectionId = meta.currentSectionId as SectionId;`,
`    if (currentSectionId) {`,
`      const section = SECTION_REGISTRY[currentSectionId];`,
`      if (section && meta.currentFieldId) {`,
`        const field = section.fields.find((f) => f.id === meta.currentFieldId);`,
`        if (field) {`,
`          expectedField = field.id;`,
`          currentQuestion = field.prompt[lang];`,
`          fieldDescription = field.name[lang];`,
`          `,
`          if (field.id === 'email') {`,
`            expectedFieldType = 'email address';`,
`            validationHints = 'Must be a valid professional email address containing @ and a valid domain name.';`,
`          } else if (field.id === 'phone') {`,
`            expectedFieldType = 'phone number';`,
`            validationHints = 'Must be a valid international or local phone number.';`,
`          } else if (field.id === 'lang') {`,
`            expectedFieldType = 'language code';`,
`            validationHints = 'Must be either Swahili ( Kiswahili, 1, sw ) or English ( English, 2, en ). Extract "sw" or "en".';`,
`          } else if (field.id === 'startYear' || field.id === 'endYear' || field.id === 'gradYear' || field.id === 'certYear') {`,
`            expectedFieldType = 'year';`,
`            validationHints = 'Must be a 4-digit number representing a year (e.g. 2021).';`,
`          } else {`,
`            expectedFieldType = 'string';`,
`            validationHints = 'Provide a concise and accurate answer.';`,
`          }`,
`        }`,
`      }`,
`    }`,
``,
`    const context = ContextBuilder.build({`,
`      language: lang,`,
`      conversationId: conversation.id,`,
`      currentSection: meta.currentSectionId,`,
`      currentState: meta.currentFieldId || 'INTRO',`,
`      lastBotMessage: meta.lastBotMessage || '',`,
`      latestUserMessage: message,`,
`      conversationHistory: [],`,
`      cvSnapshot: cv,`,
`      completedSections: meta.completedSections || [],`,
`      activeTemplate: meta.template || 'modern',`,
`      sessionMetadata: meta as any,`,
`      expectedField,`,
`      expectedFieldType,`,
`      currentQuestion,`,
`      fieldDescription,`,
`      validationHints,`,
`    });`,
``,
`    const intentResult = await this.intentEngine.evaluate(context);`,
``,
`    await this.handleIntent(intentResult, conversation, user, lang, cv, meta, message);`,
`  }`,
``,
`  private validateFieldLocally(fieldId: string, value: string): { isValid: boolean; formattedValue?: string; errorEn?: string; errorSw?: string } {`,
`    const val = value.trim();`,
`    if (!val) {`,
`      return { isValid: false, errorEn: 'Please provide an answer.', errorSw: 'Tafadhali toa jibu.' };`,
`    }`,
``,
`    const valLower = val.toLowerCase();`,
`    `,
`    if (fieldId === 'hasExperience' || fieldId === 'hasEducation') {`,
`      const isYes = ['yes', 'ndio', 'y', 'sawa'].includes(valLower);`,
`      const isNo = ['no', 'hapana', 'n', 'sina'].includes(valLower);`,
`      if (isYes) return { isValid: true, formattedValue: 'Yes' };`,
`      if (isNo) return { isValid: true, formattedValue: 'No' };`,
`      return { `,
`        isValid: false, `,
`        errorEn: 'Please reply with exactly "Yes" or "No".', `,
`        errorSw: 'Tafadhali jibu "Ndio" au "Hapana" pekee.' `,
`      };`,
`    }`,
``,
`    if (fieldId === 'startYear' || fieldId === 'endYear' || fieldId === 'certYear' || fieldId === 'gradYear') {`,
`      if (valLower === 'present' || valLower === 'sasa' || valLower === 'hadi sasa') {`,
`        return { isValid: true, formattedValue: 'Present' };`,
`      }`,
`      const yearRegex = /^\\d{4}$/;`,
`      if (!yearRegex.test(val)) {`,
`        return { `,
`          isValid: false, `,
`          errorEn: 'Please provide a valid 4-digit year (e.g., 2021) or "Present".', `,
`          errorSw: 'Tafadhali weka mwaka sahihi (k.m., 2021) au "Hadi sasa".' `,
`        };`,
`      }`,
`      return { isValid: true, formattedValue: val };`,
`    }`,
``,
`    if (fieldId === 'email') {`,
`      const emailRegex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;`,
`      if (!emailRegex.test(val)) {`,
`        return { `,
`          isValid: false, `,
`          errorEn: 'Please provide a valid email address.', `,
`          errorSw: 'Tafadhali weka barua pepe (email) iliyo sahihi.' `,
`        };`,
`      }`,
`      return { isValid: true, formattedValue: val };`,
`    }`,
``,
`    if (fieldId === 'phone' || fieldId === 'refPhone') {`,
`      const isPhoneLike = /^[\\d\\s\\+\\-\\(\\)]{7,20}$/.test(val);`,
`      const hasEmailLike = /@/.test(val);`,
`      if (fieldId === 'refPhone' && hasEmailLike) {`,
`        const emailRegex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;`,
`        if (!emailRegex.test(val)) {`,
`          return { isValid: false, errorEn: 'Please provide a valid phone or email.', errorSw: 'Tafadhali weka namba au barua pepe sahihi.' };`,
`        }`,
`        return { isValid: true, formattedValue: val };`,
`      }`,
`      `,
`      if (!isPhoneLike) {`,
`        return { `,
`          isValid: false, `,
`          errorEn: 'Please provide a valid phone number.', `,
`          errorSw: 'Tafadhali weka namba ya simu iliyo sahihi.' `,
`        };`,
`      }`,
`      return { isValid: true, formattedValue: val };`,
`    }`,
`    `,
`    if (fieldId === 'skills') {`,
`        if (/@/.test(val)) {`,
`            return { isValid: false, errorEn: 'Please provide skills, not an email address.', errorSw: 'Tafadhali weka ujuzi wako, sio barua pepe.' };`,
`        }`,
`        if (val.length < 2) return { isValid: false, errorEn: 'Please provide your skills.', errorSw: 'Tafadhali weka ujuzi wako.' };`,
`    }`,
`    `,
`    return { isValid: true, formattedValue: val };`,
`  }`,
``,
`  private async handleIntent(`,
`    intentResult: IntentResult,`,
`    conversation: Conversation,`,
`    user: User,`,
`    lang: 'sw' | 'en',`,
`    cv: CV,`,
`    meta: SessionMetadata,`,
`    message: string`,
`  ) {`,
`    const section = SECTION_REGISTRY[meta.currentSectionId as SectionId];`,
`    if (intentResult.extractedData && intentResult.extractedData.lang) {`,
`      meta.lang = intentResult.extractedData.lang as 'sw' | 'en';`,
`      lang = meta.lang;`,
`    }`,
``,
`    if (intentResult.intent === 'edit') {`,
`      const sectionName = intentResult.extractedData?.sectionToEdit;`,
`      if (sectionName) {`,
`        const nameLower = String(sectionName).toLowerCase();`,
`        let targetSection: SectionDefinition | undefined;`,
``,
`        // Try matching section by name or known keywords like 'phone', 'simu', 'email', 'address' which map to PERSONAL_INFO`,
`        const personalInfoKeywords = [`,
`          'simu', 'phone', 'email', 'address', 'jina', 'name', 'personal', 'binafsi', 'anwani',`,
`        ];`,
`        if (personalInfoKeywords.some((k) => nameLower.includes(k))) {`,
`          targetSection = ORDERED_SECTIONS.find((s) => s.id === 'PERSONAL_INFO');`,
`        } else {`,
`          for (const s of ORDERED_SECTIONS) {`,
`            if (s.id === 'REVIEW') continue;`,
`            if (`,
`              nameLower.includes(s.name.en.toLowerCase()) ||`,
`              nameLower.includes(s.name.sw.toLowerCase()) ||`,
`              s.name.en.toLowerCase().includes(nameLower) ||`,
`              s.name.sw.toLowerCase().includes(nameLower)`,
`            ) {`,
`              targetSection = s;`,
`              break;`,
`            }`,
`          }`,
`        }`,
``,
`        if (targetSection) {`,
`          this.eventBus.publish({`,
`            event: ConversationEventType.EditStarted,`,
`            timestamp: new Date().toISOString(),`,
`            conversationId: conversation.id,`,
`            userId: user.id,`,
`            section: targetSection.id,`,
`          });`,
`          if (meta.currentSectionId !== 'REVIEW' && !meta.isReviewMode) {`,
`            meta.returnToReview = false;`,
`          } else {`,
`            meta.isReviewMode = false;`,
`            meta.returnToReview = true;`,
`          }`,
`          await this.startSection(targetSection.id, conversation, user, lang, cv);`,
`          return;`,
`        }`,
`      }`,
``,
`      // If we couldn't match a section, maybe just ask them what they want to edit`,
`      const botReply =`,
`        intentResult.botReply ||`,
`        (lang === 'sw'`,
`          ? 'Umesema unataka kubadili taarifa, lakini sijui ni sehemu gani. Tafadhali taja sehemu (mfano: elimu, uzoefu).'`,
`          : 'I understand you want to edit, but I am not sure which section. Please specify (e.g., education, experience).');`,
`      await this.sendMessageAndUpdateMeta(conversation.id, user.phone, botReply, meta);`,
`      return;`,
`    }`,
``,
`    if (`,
`      intentResult.intent === 'help' ||`,
`      intentResult.intent === 'clarification' ||`,
`      intentResult.intent === 'unknown'`,
`    ) {`,
`      this.eventBus.publish({`,
`        event: ConversationEventType.ConversationPaused,`,
`        timestamp: new Date().toISOString(),`,
`        conversationId: conversation.id,`,
`        userId: user.id,`,
`      });`,
`      const reply =`,
`        intentResult.botReply ||`,
`        (lang === 'sw' ? 'Sijaelewa, tafadhali rudia.' : "I didn't understand, please try again.");`,
`      await this.sendMessageAndUpdateMeta(conversation.id, user.phone, reply, meta);`,
``,
`      this.eventBus.publish({`,
`        event: ConversationEventType.ConversationResumed,`,
`        timestamp: new Date().toISOString(),`,
`        conversationId: conversation.id,`,
`        userId: user.id,`,
`      });`,
`      // Resend current prompt`,
`      await this.sendCurrentPrompt(section, conversation, meta, user, lang);`,
`      return;`,
`    }`,
``,
`    if (intentResult.intent === 'skip') {`,
`      if (section.required) {`,
`        // Adaptive logic: If Experience is skipped, allow it but warn.`,
`        if (section.id === 'EXPERIENCE') {`,
`          const warnMsg =`,
`            lang === 'sw'`,
`              ? 'Naelewa huna uzoefu wa kazi kwa sasa. Ni sawa kabisa! Tutaangazia zaidi Elimu na Miradi yako ili kuvutia waajiri. Ungependa kuendelea bila uzoefu? (Ndio/Hapana)'`,
`              : "I understand you might not have formal work experience yet. That's completely fine! We will highlight your Education and Projects instead to impress employers. Do you want to proceed without adding experience? (Yes/No)";`,
`          meta.currentFieldId = 'CONFIRM_SKIP';`,
`          await this.saveMeta(conversation.id, meta);`,
`          await this.sendMessageAndUpdateMeta(conversation.id, user.phone, warnMsg, meta);`,
`        } else {`,
`          const warnMsg =`,
`            lang === 'sw'`,
`              ? \`Sehemu ya \${section.name.sw} ni muhimu sana kwa waajiri kwani inawasaidia kukutathmini kikamilifu. Je, una uhakika unataka kuruka sehemu hii kwa sasa? (Ndio/Hapana)\``,
`              : \`The \${section.name.en} section is highly recommended as it helps employers evaluate you comprehensively. Are you sure you want to skip this section for now? (Yes/No)\`;`,
`          meta.currentFieldId = 'CONFIRM_SKIP';`,
`          await this.saveMeta(conversation.id, meta);`,
`          await this.sendMessageAndUpdateMeta(conversation.id, user.phone, warnMsg, meta);`,
`        }`,
`      } else {`,
`        this.eventBus.publish({`,
`          event: ConversationEventType.SectionSkipped,`,
`          timestamp: new Date().toISOString(),`,
`          conversationId: conversation.id,`,
`          userId: user.id,`,
`          section: section.id,`,
`        });`,
`        await this.completeSection(section, conversation, user, lang, cv, meta, true);`,
`      }`,
`      return;`,
`    }`,
``,
`    if (meta.currentFieldId === 'CONFIRM_SKIP') {`,
`      const ans = message.trim().toLowerCase();`,
`      // Check for positive confirmation of skipping (Yes)`,
`      const isYes =`,
`        ans === 'yes' ||`,
`        ans === 'ndio' ||`,
`        ans === 'y' ||`,
`        ans === 'sawa' ||`,
`        ans === 'sawa kabisa' ||`,
`        ans === 'skip' ||`,
`        ans === 'ruka' ||`,
`        ans.startsWith('yes ') ||`,
`        ans.startsWith('ndio ');`,
``,
`      // Check for negative confirmation of skipping (No / fill in details)`,
`      const isNo =`,
`        ans === 'no' ||`,
`        ans === 'hapana' ||`,
`        ans === 'n' ||`,
`        ans === 'si sahihi' ||`,
`        ans.startsWith('no ') ||`,
`        ans.startsWith('hapana ') ||`,
`        ans.includes('change my mind') ||`,
`        ans.includes('badili mawazo') ||`,
`        ans.includes('nitaweka') ||`,
`        ans.includes('nitajaza');`,
``,
`      if (isYes) {`,
`        this.eventBus.publish({`,
`          event: ConversationEventType.SectionSkipped,`,
`          timestamp: new Date().toISOString(),`,
`          conversationId: conversation.id,`,
`          userId: user.id,`,
`          section: section.id,`,
`        });`,
`        await this.completeSection(section, conversation, user, lang, cv, meta, true);`,
`      } else if (isNo) {`,
`        meta.currentFieldId = section.fields.length > 0 ? section.fields[0].id : 'DONE';`,
`        await this.saveMeta(conversation.id, meta);`,
`        await this.sendCurrentPrompt(section, conversation, meta, user, lang);`,
`      } else {`,
`        // Under CONFIRM_SKIP, if the user asks questions or for clarification, we let the Intent Engine's AI reply naturally`,
`        if (intentResult.botReply) {`,
`          await this.sendMessageAndUpdateMeta(conversation.id, user.phone, intentResult.botReply, meta);`,
`        } else {`,
`          const fallback =`,
`            lang === 'sw'`,
`              ? 'Sikuelewa vizuri. Tafadhali thibitisha kwa kujibu *Ndio* kama ungependa kuruka sehemu hii, au *Hapana* ili tuijaze sasa.'`,
`              : "I didn't quite catch that. Please confirm by replying *Yes* to skip this section, or *No* to fill it in now.";`,
`          await this.sendMessageAndUpdateMeta(conversation.id, user.phone, fallback, meta);`,
`        }`,
`      }`,
`      return;`,
`    }`,
``,
`    if (intentResult.intent === 'confirmation') {`,
`      if (meta.pendingConfirmationData) {`,
`        // Confirming AI extracted data`,
`        // Assume yes for now, could be yes/no`,
`        await this.applyExtractedData(meta.pendingConfirmationData, cv);`,
`        meta.pendingConfirmationData = undefined;`,
`        await this.advanceField(`,
`          section,`,
`          conversation,`,
`          user,`,
`          lang,`,
`          cv,`,
`          meta,`,
`          meta.pendingConfirmationData`,
`        );`,
`        return;`,
`      }`,
`    }`,
``,
`    if (intentResult.intent === 'answer' || intentResult.intent === 'correction') {`,
`      if (meta.skipConfirmed) meta.skipConfirmed = false; // Reset`,
``,
`      if (intentResult.requiresConfirmation) {`,
`        meta.pendingConfirmationData = intentResult.extractedData;`,
`        await this.saveMeta(conversation.id, meta);`,
`        const confirmMsg =`,
`          lang === 'sw'`,
`            ? 'Nimeelewa: ' + JSON.stringify(intentResult.extractedData) + '. Ni sahihi?'`,
`            : 'I understood: ' + JSON.stringify(intentResult.extractedData) + '. Is this correct?';`,
`        await this.sendMessageAndUpdateMeta(conversation.id, user.phone, confirmMsg, meta);`,
`        return;`,
`      }`,
``,
`      if (meta.currentFieldId && meta.currentFieldId !== 'ADD_ANOTHER' && meta.currentFieldId !== 'CONFIRM_SKIP' && meta.currentFieldId !== 'DONE') {`,
`          let extractedVal = (intentResult.extractedData && intentResult.extractedData[meta.currentFieldId]) ? intentResult.extractedData[meta.currentFieldId] : message.trim();`,
`          const validation = this.validateFieldLocally(meta.currentFieldId, extractedVal);`,
`          if (!validation.isValid) {`,
`              const errMsg = lang === 'sw' ? validation.errorSw : validation.errorEn;`,
`              const field = section.fields.find(f => f.id === meta.currentFieldId);`,
`              const prompt = errMsg + '\\n\\n' + (field ? field.prompt[lang] : '');`,
`              await this.sendMessageAndUpdateMeta(conversation.id, user.phone, prompt, meta);`,
`              return;`,
`          }`,
`          `,
`          const finalVal = validation.formattedValue || extractedVal;`,
`          `,
`          if (!intentResult.extractedData) intentResult.extractedData = {};`,
`          `,
`          // STRICT MAPPING`,
`          intentResult.extractedData = { [meta.currentFieldId]: finalVal };`,
`          await this.applyExtractedData(intentResult.extractedData, cv);`,
`          `,
`          // BOOLEAN SKIP LOGIC`,
`          if ((meta.currentFieldId === 'hasExperience' || meta.currentFieldId === 'hasEducation') && finalVal === 'No') {`,
`              await this.completeSection(section, conversation, user, lang, cv, meta, true);`,
`              return;`,
`          }`,
`      } else if (intentResult.extractedData && (meta.currentFieldId === 'DONE' || meta.currentFieldId === 'CONFIRM_SKIP' || meta.currentFieldId === 'ADD_ANOTHER')) {`,
`          await this.applyExtractedData(intentResult.extractedData, cv);`,
`      }`,
``,
`      // 3. ADD_ANOTHER LOOP FIX`,
`      if (meta.currentFieldId === 'ADD_ANOTHER') {`,
`        const ans = message.trim().toLowerCase();`,
`        const isYes = ans === 'yes' || ans === 'ndio' || ans === 'y' || ans === 'ongeza' || ans.includes('add') || ans.includes('ndiyo');`,
`        const isNo = ans === 'no' || ans === 'hapana' || ans === 'n' || ans.includes('continue') || ans.includes('endelea') || ans === 'sawa' || ans.includes('done');`,
`        if (isYes) {`,
`            meta.currentFieldId = section.fields[0].id;`,
`            await this.saveMeta(conversation.id, meta);`,
`            await this.sendCurrentPrompt(section, conversation, meta, user, lang);`,
`            return;`,
`        } else if (isNo) {`,
`            await this.completeSection(section, conversation, user, lang, cv, meta, false);`,
`            return;`,
`        } else {`,
`            const botReply = lang === 'sw' ? 'Tafadhali jibu Ndio (kuongeza) au Hapana (kumaliza).' : 'Please reply Yes (to add another) or No (to finish section).';`,
`            await this.sendMessageAndUpdateMeta(conversation.id, user.phone, botReply, meta);`,
`            return;`,
`        }`,
`      }`,
``,
`      await this.advanceField(`,
`        section,`,
`        conversation,`,
`        user,`,
`        lang,`,
`        cv,`,
`        meta,`,
`        intentResult.extractedData,`,
`        intentResult.botReply`,
`      );`,
`      return;`,
`    }`,
``,
`    // Default catch-all`,
`    await this.sendCurrentPrompt(section, conversation, meta, user, lang);`,
`  }`,
``,
`  private async applyExtractedData(data: Record<string, any>, cv: CV) {`,
`    await CVDataUpdater.updateCV(cv.id, data);`,
`  }`,
``,
`  private async startSection(`,
`    sectionId: SectionId,`,
`    conversation: Conversation,`,
`    user: User,`,
`    lang: 'sw' | 'en',`,
`    cv: CV`,
`  ) {`,
`    const section = SECTION_REGISTRY[sectionId];`,
`    if (!section) return;`,
``,
`    this.eventBus.publish({`,
`      event: ConversationEventType.SectionStarted,`,
`      timestamp: new Date().toISOString(),`,
`      conversationId: conversation.id,`,
`      userId: user.id,`,
`      section: sectionId,`,
`    });`,
``,
`    const meta = (`,
`      typeof conversation.metadata === 'object' && conversation.metadata !== null`,
`        ? conversation.metadata`,
`        : {}`,
`    ) as SessionMetadata;`,
``,
`    if (section.id === 'REVIEW') {`,
`      meta.isReviewMode = true;`,
`    }`,
`    meta.currentSectionId = sectionId;`,
`    meta.currentFieldId = section.fields.length > 0 ? section.fields[0].id : 'DONE';`,
`    meta.skipConfirmed = false;`,
`    meta.pendingConfirmationData = undefined;`,
``,
`    // Show Progress`,
`    await this.showProgress(section, conversation, meta, user, lang);`,
``,
`    let intro = section.introPrompt[lang];`,
`    if (section.id === 'REVIEW') {`,
`      intro += '\\n\\n' + (await this.buildReviewText(cv, meta, lang));`,
`    }`,
`    if (intro && intro.trim() !== '') {`,
`      await this.sendMessageAndUpdateMeta(conversation.id, user.phone, intro, meta);`,
`    }`,
``,
`    await this.saveMeta(conversation.id, meta);`,
``,
`    if (meta.currentFieldId !== 'DONE') {`,
`      await this.sendCurrentPrompt(section, conversation, meta, user, lang);`,
`    } else {`,
`      // Review section is practically "done" fields-wise`,
`      if (sectionId !== 'REVIEW') {`,
`        await this.completeSection(section, conversation, user, lang, cv, meta, false);`,
`      }`,
`    }`,
`  }`,
``,
`  private async advanceField(`,
`    section: SectionDefinition,`,
`    conversation: Conversation,`,
`    user: User,`,
`    lang: 'sw' | 'en',`,
`    cv: CV,`,
`    meta: SessionMetadata,`,
`    extractedData?: Record<string, any>,`,
`    botReply?: string`,
`  ) {`,
`    let currentIndex = section.fields.findIndex((f) => f.id === meta.currentFieldId);`,
``,
`    if (currentIndex === -1 || currentIndex >= section.fields.length - 1) {`,
`      if (section.isMultiItem && meta.currentFieldId !== 'ADD_ANOTHER') {`,
`        meta.currentFieldId = 'ADD_ANOTHER';`,
`        await this.saveMeta(conversation.id, meta);`,
`        let prompt =`,
`          lang === 'sw'`,
`            ? 'Je, ungependa kuongeza nyingine? (Ndio/Hapana)'`,
`            : 'Would you like to add another? (Yes/No)';`,
`        if (botReply) {`,
`          prompt = \`\${botReply.trim()}\\n\\n\${prompt}\`;`,
`        }`,
`        await this.sendMessageAndUpdateMeta(conversation.id, user.phone, prompt, meta);`,
`        return;`,
`      }`,
`      if (meta.currentFieldId === 'ADD_ANOTHER') {`,
`        // For now we assume complete.`,
`      }`,
`      await this.completeSection(section, conversation, user, lang, cv, meta, false);`,
`    } else {`,
`      const nextField = section.fields[currentIndex + 1];`,
`      meta.currentFieldId = nextField.id;`,
`      await this.saveMeta(conversation.id, meta);`,
`      await this.sendCurrentPrompt(section, conversation, meta, user, lang, botReply);`,
`    }`,
`  }`,
``,
`  private async sendCurrentPrompt(`,
`    section: SectionDefinition,`,
`    conversation: Conversation,`,
`    meta: SessionMetadata,`,
`    user: User,`,
`    lang: 'sw' | 'en',`,
`    botReply?: string`,
`  ) {`,
`    const field = section.fields.find((f) => f.id === meta.currentFieldId);`,
`    if (field) {`,
`      let prompt = field.prompt[lang];`,
``,
`      if (botReply) {`,
`        prompt = \`\${botReply.trim()}\\n\\n\${prompt}\`;`,
`      }`,
``,
`      await this.sendMessageAndUpdateMeta(conversation.id, user.phone, prompt, meta);`,
`    }`,
`  }`,
``,
`  private async completeSection(`,
`    section: SectionDefinition,`,
`    conversation: Conversation,`,
`    user: User,`,
`    lang: 'sw' | 'en',`,
`    cv: CV,`,
`    meta: SessionMetadata,`,
`    skipped: boolean`,
`  ) {`,
`    if (!meta.completedSections) meta.completedSections = [];`,
`    if (!meta.skippedSections) meta.skippedSections = [];`,
``,
`    if (skipped) {`,
`      if (!meta.skippedSections.includes(section.id)) meta.skippedSections.push(section.id);`,
`    } else {`,
`      if (!meta.completedSections.includes(section.id)) meta.completedSections.push(section.id);`,
`    }`,
``,
`    this.eventBus.publish({`,
`      event: ConversationEventType.SectionCompleted,`,
`      timestamp: new Date().toISOString(),`,
`      conversationId: conversation.id,`,
`      userId: user.id,`,
`      section: section.id,`,
`    });`,
``,
`    // Show rewarding message only if returning to review, to avoid duplicating the next section's intro prompt`,
`    if (!skipped && section.id !== 'REVIEW' && meta.returnToReview) {`,
`      const ack = this.getAcknowledgement(lang);`,
`      const reward =`,
`        lang === 'sw'`,
`          ? \`\${ack} \${section.name.sw} imeongezwa kikamilifu.\``,
`          : \`\${ack} Your \${section.name.en} has been successfully updated.\`;`,
`      await this.sendMessageAndUpdateMeta(conversation.id, user.phone, reward, meta);`,
`    }`,
``,
`    if (meta.returnToReview) {`,
`      meta.returnToReview = false;`,
`      await this.startSection('REVIEW', conversation, user, lang, cv);`,
`    } else {`,
`      const currentIndex = ORDERED_SECTIONS.findIndex((s) => s.id === section.id);`,
`      if (currentIndex < ORDERED_SECTIONS.length - 1) {`,
`        const nextSection = ORDERED_SECTIONS[currentIndex + 1];`,
`        await this.startSection(nextSection.id, conversation, user, lang, cv);`,
`      } else {`,
`        // Finished Review!`,
`        const endMsg =`,
`          lang === 'sw'`,
`            ? 'Hongera! CV yako imekamilika. Tutaandaa PDF sasa.'`,
`            : 'Congratulations! Your CV is complete. We will generate the PDF now.';`,
`        await this.sendMessageAndUpdateMeta(conversation.id, user.phone, endMsg, meta);`,
`      }`,
`    }`,
`  }`,
``,
`  private async showProgress(`,
`    section: SectionDefinition,`,
`    conversation: Conversation,`,
`    meta: SessionMetadata,`,
`    user: User,`,
`    lang: 'sw' | 'en'`,
`  ) {`,
`    if (section.id === 'WELCOME' || section.id === 'LANGUAGE_SELECTION') return;`,
`    const total = ORDERED_SECTIONS.filter(s => s.id !== 'REVIEW' && s.id !== 'WELCOME' && s.id !== 'LANGUAGE_SELECTION').length;`,
`    const current = section.order;`,
``,
`    let msg = lang === 'sw' ? '📊 *Maendeleo Yako:*\\n\\n' : '📊 *Live Progress:*\\n\\n';`,
``,
`    const comp: string[] = [];`,
`    let next = null;`,
`    let remain = 0;`,
`    ORDERED_SECTIONS.forEach((s) => {`,
`      if (s.id === 'REVIEW' || s.id === 'WELCOME' || s.id === 'LANGUAGE_SELECTION') return;`,
`      if (meta.completedSections?.includes(s.id) || meta.skippedSections?.includes(s.id)) {`,
`        comp.push(s.name[lang]);`,
`      } else if (s.id === section.id) {`,
`        next = s.name[lang];`,
`      } else if (s.order > current) {`,
`        remain++;`,
`      }`,
`    });`,
``,
`    if (comp.length > 0) {`,
`      msg += \`✅ Kamili: \${comp.length}/\${total}\\n\`;`,
`    }`,
`    if (next) {`,
`      msg += \`➡️ Inayofuata: *\${next}*\\n\`;`,
`    }`,
`    if (remain > 0) {`,
`      msg += lang === 'sw' ? \`\\nZilizobaki: \${remain}\\n\` : \`\\nRemaining: \${remain}\\n\`;`,
`    }`,
`    await this.sendMessageAndUpdateMeta(conversation.id, user.phone, msg, meta);`,
`  }`,
``,
`  private async buildReviewText(cv: CV, meta: SessionMetadata, lang: 'sw' | 'en'): Promise<string> {`,
`    let msg = lang === 'sw' ? '📋 *Uhakiki wa CV Yako:*\\n\\n' : '📋 *Review your CV:*\\n\\n';`,
`    ORDERED_SECTIONS.forEach((s) => {`,
`      if (s.id === 'REVIEW' || s.id === 'WELCOME' || s.id === 'LANGUAGE_SELECTION') return;`,
`      const isSkipped = meta.skippedSections?.includes(s.id);`,
`      const isCompleted = meta.completedSections?.includes(s.id);`,
`      let status = '';`,
`      if (isSkipped) status = '⏭️';`,
`      else if (isCompleted) status = '✓';`,
`      else status = '❌';`,
``,
`      msg += \`\${status} \${s.name[lang]}\\n\`;`,
`    });`,
`    const askStr =`,
`      lang === 'sw'`,
`        ? '\\nJe, ungependa kurekebisha chochote kabla sijatengeneza CV yako?\\n(Andika "hariri [sehemu]" kurekebisha au "Sahihi" kumaliza)'`,
`        : '\\nWould you like to edit anything before I generate your professional CV?\\n(Type "edit [section]" to change something, or "Yes" to finish)';`,
`    msg += askStr;`,
`    return msg;`,
`  }`,
``,
`  private async handleReviewMode(`,
`    message: string,`,
`    conversation: Conversation,`,
`    user: User,`,
`    lang: 'sw' | 'en',`,
`    cv: CV,`,
`    meta: SessionMetadata`,
`  ): Promise<boolean> {`,
`    const msgLower = message.toLowerCase();`,
`    if (`,
`      msgLower.includes('correct') ||`,
`      msgLower.includes('sahihi') ||`,
`      msgLower.includes('yes') ||`,
`      msgLower.includes('ndio') ||`,
`      msgLower.includes('generate')`,
`    ) {`,
`      this.eventBus.publish({`,
`        event: ConversationEventType.ReviewCompleted,`,
`        timestamp: new Date().toISOString(),`,
`        conversationId: conversation.id,`,
`        userId: user.id,`,
`      });`,
``,
`      const endMsg =`,
`        lang === 'sw'`,
`          ? 'Tunatengeneza CV yako kitaalam sasa (inaweza kuchukua sekunde chache)...'`,
`          : 'Enhancing and generating your professional CV now (this may take a few seconds)...';`,
`      await this.sendMessageAndUpdateMeta(conversation.id, user.phone, endMsg, meta);`,
``,
`      // Step 1: Authoring Pipeline`,
`      const enhancementResult = await this.authoringService.enhanceCV(cv, lang);`,
``,
`      if (!enhancementResult.success) {`,
`        logger.error(\`[FSMEngine] Authoring Service failed: \${enhancementResult.reason}\`);`,
`      }`,
``,
`      const finalCVData = enhancementResult.success ? enhancementResult.data : cv;`,
``,
`      if (enhancementResult.success && enhancementResult.consistency?.hasInconsistencies) {`,
`        logger.warn(`,
`          \`[FSMEngine] CV Consistency warnings found: \${JSON.stringify(enhancementResult.consistency.inconsistencies)}\``,
`        );`,
`      }`,
``,
`      // Update CV in DB with final data`,
`      await this.cvService.updateCV(cv.id, {`,
`        professionalSummary: finalCVData.professionalSummary,`,
`        experience: finalCVData.experience,`,
`        skills: finalCVData.skills,`,
`        education: finalCVData.education,`,
`        projects: finalCVData.projects,`,
`      });`,
``,
`      // Step 2: Generate PDF`,
`      const htmlContent = this.cvPreviewService.generateHtml(user, finalCVData);`,
`      const pdfUrl = await this.pdfService.generatePDF(htmlContent, \`CV_\${user.id}.pdf\`);`,
`      if (pdfUrl) {`,
`        await this.sendMessageAndUpdateMeta(conversation.id, user.phone, lang === 'sw' ? \`Asante kwa kutumia CareerBot! CV yako ipo tayari: \${pdfUrl}\` : \`Thank you for using CareerBot! Your CV is ready: \${pdfUrl}\`, meta);`,
`        for (const key in meta) delete (meta as any)[key];`,
`        await this.convService.updateConversation(conversation.id, { currentState: 'COMPLETED', metadata: meta as any });`,
`      } else {`,
`        await this.sendMessageAndUpdateMeta(conversation.id, user.phone, 'Error generating PDF.', meta);`,
`      }`,
`      return true;`,
`    }`,
`    return false;`,
`  }`,
``,
`  private getAcknowledgement(lang: 'sw' | 'en'): string {`,
`    const sw = [`,
`      'Safi sana!',`,
`      'Kazi nzuri!',`,
`      'Tumepata maelezo hayo, vizuri sana.',`,
`      'Sawa kabisa, imekamilika vyema.',`,
`      'Ushirikiano wako ni mzuri sana.',`,
`      'Marekebisho yamehifadhiwa vizuri.',`,
`      'Safi mno!',`,
`      'Hakika, taarifa hizi zitafanya CV yako kuvutia zaidi.',`,
`    ];`,
`    const en = [`,
`      'Wonderful!',`,
`      'Perfect, got that.',`,
`      'That makes total sense.',`,
`      'Excellent progress!',`,
`      'Thank you, that is clear.',`,
`      'Beautifully phrased!',`,
`      'Got it. This is shaping up nicely.',`,
`      'Indeed, this details your background perfectly.',`,
`      'Fantastic!',`,
`    ];`,
`    const arr = lang === 'sw' ? sw : en;`,
`    return arr[Math.floor(Math.random() * arr.length)];`,
`  }`,
`  private async saveMeta(conversationId: string, meta: SessionMetadata) {`,
`    await this.convService.updateConversation(conversationId, { metadata: meta as any });`,
`  }`,
`}`,
];

fs.writeFileSync('src/conversation/fsm/FSMEngine.ts', lines.join('\n'));
