export enum ConversationState {
  WELCOME = 'WELCOME',
  SELECT_LANGUAGE = 'SELECT_LANGUAGE',
  REGISTER_NAME = 'REGISTER_NAME',
  REGISTER_EMAIL = 'REGISTER_EMAIL',
  HOME = 'HOME',
  CV_JOB_TITLE = 'CV_JOB_TITLE',
  CV_SUMMARY = 'CV_SUMMARY',
  
  // Experience
  EXP_COMPANY = 'EXP_COMPANY',
  EXP_JOB_TITLE = 'EXP_JOB_TITLE',
  EXP_LOCATION = 'EXP_LOCATION',
  EXP_TYPE = 'EXP_TYPE',
  EXP_START_MONTH = 'EXP_START_MONTH',
  EXP_START_YEAR = 'EXP_START_YEAR',
  EXP_STILL_WORKING = 'EXP_STILL_WORKING',
  EXP_END_MONTH = 'EXP_END_MONTH',
  EXP_END_YEAR = 'EXP_END_YEAR',
  EXP_RESPONSIBILITIES = 'EXP_RESPONSIBILITIES',
  EXP_ACHIEVEMENTS = 'EXP_ACHIEVEMENTS',
  EXP_ADD_ANOTHER = 'EXP_ADD_ANOTHER',

  // Education
  EDU_INSTITUTION = 'EDU_INSTITUTION',
  EDU_QUALIFICATION = 'EDU_QUALIFICATION',
  EDU_FIELD = 'EDU_FIELD',
  EDU_START_YEAR = 'EDU_START_YEAR',
  EDU_GRAD_YEAR = 'EDU_GRAD_YEAR',
  EDU_GPA = 'EDU_GPA',
  EDU_ADD_ANOTHER = 'EDU_ADD_ANOTHER',

  // Skills
  CV_SKILLS = 'CV_SKILLS',

  // Languages
  LANG_NAME = 'LANG_NAME',
  LANG_LEVEL = 'LANG_LEVEL',
  LANG_ADD_ANOTHER = 'LANG_ADD_ANOTHER',

  // References
  REF_NAME = 'REF_NAME',
  REF_POSITION = 'REF_POSITION',
  REF_COMPANY = 'REF_COMPANY',
  REF_PHONE = 'REF_PHONE',
  REF_EMAIL = 'REF_EMAIL',
  REF_ADD_ANOTHER = 'REF_ADD_ANOTHER',

  AI_PROCESSING = 'AI_PROCESSING',
  CV_PREVIEW = 'CV_PREVIEW',
  EDIT_SECTION_SELECT = 'EDIT_SECTION_SELECT',
  PDF_READY = 'PDF_READY',
  EXPIRED_PROMPT = 'EXPIRED_PROMPT',
}
